# Project information
site_name: "Antonio Feijao UK, Cyber Security Architect, learning by doing."
site_url: https://www.antoniofeijao.com/
site_author: Antonio Feijao UK
site_description: >-
  Antonio Feijao UK, Cyber Security Architect @GenomicsEngland.
  Expertise and skills in AWS, Networking, Security, Infrastructure, CyberSecurity, Linux, MacOS, Python

# Copyright
copyright: >
  Copyright &copy; 2025,
  <a href="https://www.antoniofeijao.com/">Antonio Feijao UK</a>.
  All rights reserved.

theme:
  name: material
  favicon: /favicon.ico
  logo: assets/images/Antonio-Feijao-UK.jpeg
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
  highlightjs: true
  hljs_languages:
    - yaml
  shortcuts:
    help: 72      # h
    next: 78      # n
    previous: 80  # p
    search: 83    # s
  navigation_depth: 4
  language: en
  palette:
    name: "color-scheme-dark"
    scheme: slate
    primary: black
    accent: deep orange
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  font: false

extra:
  generator: false
  social:
    - icon: fontawesome/solid/house
      link: https://www.antoniofeijao.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/antoniofeijaouk
    - icon: fontawesome/brands/github
      link: https://github.com/AntonioFeijaoUK

# Navigation
# nav:
#   - Home:  index.md
#   - News:  news/index.md  # The index file will now render a dynamic tree of news articles.
#   - Pages: pages/index.md
#   - Contact: contact.md
#   - About: about-me/index.md

# Plugins
plugins:
  - privacy  # Plugin for privacy compliance.
  # - mkdocstrings  # Uncomment if documentation string extraction is required.
  #- glob  # Plugin to enable glob patterns in the navigation.
  - social:
      enabled: true  # Enable social plugin.
  - blog:
      enabled: true
      blog_dir: .
      post_date_format: full
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 3
      excerpt_separator: "<!-- more -->"
  - search:
      enabled: true
      lang: en
  - macros:
      enabled: true
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: iso_datetime
      fallback_to_build_date: true
  - tags:
      enabled: true
  - pagetree: # Plugin to auto-generate the page tree.
      enabled: true
      #root: news
  # - sitemap:
  #     changefreq: daily
  #     priority: 0.5
  # - mkdocs-seo-plugin:
  #     site_name: "Antonio Feijao UK"
  #     description: "Cyber Security Architect Blog"

# Markdown Extensions
markdown_extensions:
  # Standard Python Markdown Extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # pymdown extensions for enhanced Markdown capabilities.
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

