title: "Antonio Feijao UK – Cyber Security Architect Learning by Doing"
description: "Insights and projects by Antonio Feijao, UK Security Architect at Genomics England. Expertise in AWS, Networking, Security, Infrastructure, Linux, macOS, and Python 3."

url: "https://www.antoniofeijao.com/"
baseurl: ""

locale: en_GB

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag

collections:
  stories:
    output: true
    permalink: /stories/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      path: ""
      type: "stories"
    values:
      layout: default

# SEO / metadata improvements
author: "Antonio Feijao"
twitter:
  card: summary

exclude:
  - README.md
  - LICENSE
