remote_theme: pages-themes/minimal@v0.2.0
#theme: jekyll-theme-minimal

plugins:
- jekyll-remote-theme 
# - jekyll-redirect-from

encoding: "utf-8"

locale: en

title_separator: "-"

title: Antonio Feijao in UK - AWS Infrastructure Architect with Networking and Security Specialism
    
description: Antonio Feijao in UK whoami and about personal website.

logo: https://avatars.githubusercontent.com/u/2548084

#/assets/img/logo.png

show_downloads: false #  ["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
