#remote_theme: pages-themes/minimal@v0.2.0
#theme: jekyll-theme-minimal

url: "https://antoniofeijao.com" # the base hostname & protocol for your site
  
plugins:
- jekyll-sitemap
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag


# - jekyll-redirect-from

encoding: "utf-8"

locale: en

title_separator: "-"

title: Antonio Feijao - AWS Infrastructure Architect with Networking and Security Specialism
    
description: Antonio Feijao, AWS Infrastructure Architect with Networking and Security Specialism personal website.

logo: https://pbs.twimg.com/profile_images/1035490485522063361/SzamsrVO_400x400.jpg
#https://avatars.githubusercontent.com/u/2548084

#/assets/img/logo.png

show_downloads: false #  ["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

theme: jekyll-theme-slate
