# source https://squidfunk.github.io/mkdocs-material/publishing-your-site/?h=actions#with-github-actions
name: ci 
on:
  push:
    branches:
      - www-mkdocs-material-v01
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Generate News Index
        run: |
          NEWS_DIR=docs/news
          INDEX_FILE=${NEWS_DIR}/index.md
          echo "# News" > "$INDEX_FILE"
          echo "" >> "$INDEX_FILE"
          echo "{{ pagetree(root='news') }}" >> "$INDEX_FILE"
      # - name: Generate News Index
      #   run: |
      #     NEWS_DIR=docs/news
      #     INDEX_FILE=${NEWS_DIR}/index.md
      #     echo "# News" > "$INDEX_FILE"
      #     echo "" >> "$INDEX_FILE"
      #     for file in "$NEWS_DIR"/*.md; do
      #       if [ "$(basename "$file")" = "index.md" ]; then
      #         continue
      #       fi
      #       filename=$(basename "$file")
      #       title="${filename%.md}"
      #       echo "- [${title}](${filename})" >> "$INDEX_FILE"
      #     done
      - name: Generate Pages Index
        run: |
          NEWS_DIR=docs/pages
          INDEX_FILE=${NEWS_DIR}/index.md
          echo "# Pages" > "$INDEX_FILE"
          echo "" >> "$INDEX_FILE"
          for file in "$NEWS_DIR"/*.md; do
            if [ "$(basename "$file")" = "index.md" ]; then
              continue
            fi
            filename=$(basename "$file")
            title="${filename%.md}"
            echo "- [${title}](${filename})" >> "$INDEX_FILE"
          done
      - name: Generate About-Me Index
        run: |
          NEWS_DIR=docs/about-me
          INDEX_FILE=${NEWS_DIR}/index.md
          echo "# About-Me" > "$INDEX_FILE"
          echo "" >> "$INDEX_FILE"
          for file in "$NEWS_DIR"/*.md; do
            if [ "$(basename "$file")" = "index.md" ]; then
              continue
            fi
            filename=$(basename "$file")
            title="${filename%.md}"
            echo "- [${title}](${filename})" >> "$INDEX_FILE"
          done
      #- run: pip install mkdocstrings
      #- run: pip install mkdocs-material 
      - run: pip install "mkdocs-material[imaging]"
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-pagetree-plugin
      - run: mkdocs gh-deploy --force
